export const API_ROUTES = {
  LOGIN: "/api/auth/login",
  LOGOUT: "/api/auth/logout",
  ME: "/api/auth/me",
  REFRESH_TOKEN: "/api/auth/refresh",
  FORGOT_PASSWORD: "/api/auth/forgot-password",
  SEND_OTP: "/api/auth/send-otp",
  VERIFY_OTP: "/api/auth/verify-otp",
  RESET_PASSWORD: "/api/auth/reset-password",
  PRODUCTS: "/api/admin/products",
  ORDERS: "/api/admin/orders",
  BRANDS: "/api/brands",
  ADMIN_BRANDS: "/api/admin/brands",
  CATEGORIES: "/api/categories",
  ADMIN_CATEGORIES: "/api/admin/categories",
  CONCENTRATIONS: "/api/concentrations",
  ADMIN_CONCENTRATIONS: "/api/admin/concentrations",
  ATTRIBUTES: "/api/admin/attributes",
  WAREHOUSES: "/api/admin/warehouses",
  USERS: "/api/admin/users",
  ROLES: "/api/admin/roles",
  UPLOAD: "/api/admin/upload",
};
